name: Eve-Sch CD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-n-push:
    env:
      GOOS: linux
      GOARCH: amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.7'
      - run: go version

      - name: Set variables ‚ú®
        run: |          
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
          TS=$(date -u +%F_%TUTC)
          echo "BUILD_TIME=$TS" >> $GITHUB_ENV
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          BUILD_HOST=$(hostname)
          echo "BUILD_HOST=$BUILD_HOST" >> $GITHUB_ENV

      - name: Test üß†
        run: |
          go get ./...
          go test ./... -v -race

      - name: Set up Docker Buildx üê≥
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Cache Docker layers üê≥
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Docker Image üê≥
        if: ${{ contains(github.ref, 'master') }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          buildArgs: |
            VERSION=${{ env.VERSION }}
            SHA=${{ github.sha }}
            SHORT_SHA=${{ env.SHORT_SHA }}
            AUTHOR='${{ github.actor }}' 
            BUILD_HOST='${{ env.BUILD_HOST }}' 
            BRANCH=${{ github.ref }}
            BUILD_DATE='${{ env.BUILD_TIME }}' 
            PRERELEASE=''            
          tags: |
            unanet/eve-sch:latest
            unanet/eve-sch:${{ env.VERSION }}
